services:
  - type: web
    name: stashi-control-plane
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_DB_HOST
        sync: false
      - key: NEXT_PUBLIC_DB_PORT
        sync: false
      - key: CONTROL_PLANE_DATABASE_URL
        sync: false
      - key: STASHI_AGENT_SHARED_SECRET
        sync: false
      - key: R2_ENDPOINT
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: BACKUP_BUCKET
        sync: false
